# Generated by Django 3.0.4 on 2020-03-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
